from pathlib import Path


NO_CENTER_IDX = -1

PROJECT_ROOT = Path(__file__).parent.parent
COUNTRIES_DATA_ROOT = PROJECT_ROOT / "countries_data"


TARGET_NODE_CODE_FIELD_NAME = "NODE_1_CODE"
TARGET_NODE_NAME_FIELD_NAME = "NODE_1_NAME"
SOURCE_NODE_CODE_FIELD_NAME = "NODE_2_CODE"
SOURCE_NODE_NAME_FIELD_NAME = "NODE_2_NAME"
INCOMING_FLOW_FIELD_NAME = "INCOMING_FLOW"

DEBUG_OUTPUT_FOLDER = "debug_output"

TQDM_COLS_COUNT = 100
DEFAULT_ASSIGNMENT_OUTPUT_FILE_NAME = "assignment"
